site_name: Data Structures and Algorithms Guide 
theme:
  name: windmill
nav:
  - Home: index.html
  - Graph:
    - Detect Cycle in Directed Graph: graph/detect_cycle_in_directed_graph.md
plugins:
  - search
  - mermaid2