site_name: Data Structures and Algorithms Guide
theme:
  name: windmill
nav:
  - Math:
      - Formulas: math/formulas.md
  - Matrices:
      - Operations on Matrices: matrix/matrix_operations.md
  - Disjoint Set:
      - Union-Find Algorithm: disjoint_set/union_find.md
  - Graph:
      - Detect Cycle in Directed Graph: graph/detect_cycle_in_directed_graph.md
      - Dijkstra Shortest Path: graph/dijkstra_shortest_path.md
  - Heap:
      - Priority Queue: heap/priority_queue.md
  - Backtracking:
      - Backtracking: backtracking/backtracking.md
  - Dynamic Programming:
      - Longest Common Subsequence: dynamic_programming/longest_common_subsequence.md
  - Tips & Tricks in Java:
      - Lamda Expression & Streams: tricks_in_java/lambda_stream.md
plugins:
  - search
  - mermaid2
