site_name: Data Structures and Algorithms Guide
theme:
  name: material
nav:
  - Math:
      - Formulas: math/formulas.md
  - Matrices:
      - Operations on Matrices: matrix/matrix_operations.md
  - Disjoint Set:
      - Union-Find Algorithm: disjoint_set/union_find.md
  - Graph:
      - Detect Cycle in Directed Graph: graph/detect_cycle_in_directed_graph.md
      - Dijkstra Shortest Path: graph/dijkstra_shortest_path.md
      - Bellman Ford Shortest Path: graph/bellman_ford_algorithm.md
  - Tree:
      - Heap: tree/heap.md
  - Recursion:
      - Recursion: recursion/recursion.md
      - Backtracking: recursion/backtracking.md
  - Dynamic Programming:
      - Longest Common Subsequence: dynamic_programming/longest_common_subsequence.md
  - Tips & Tricks in Java:
      - Lamda Expression & Streams: tricks_in_java/lambda_stream.md
plugins:
  - search
  - mermaid2
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML